[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "identifiers-pl"
description = "Validate Polish identifiers (NIP, PESEL, REGON) and IBAN numbers"
dynamic = ["version"]
authors = [{name = "blockersiontko", email = "i.settingidofirefox@gmail.com"}]
keywords = ["CLI", "PESEL", "NIP", "REGON", "IBAN", "validation"]
requires-python = ">=3.11"
readme = "README.md"
license = "MIT"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = ["black", "pytest", "pytest-cov"]

[project.scripts]
identifiers-pl = "identifiers_pl.__main__:main"

[project.urls]
Homepage = "https://github.com/blockersiontko/identifiers-pl"

[tool.setuptools.packages.find]
include = ["identifiers_pl*"]

[tool.setuptools.dynamic]
version = {file = "VERSION.md"}

[tool.black]
line-length = 88